# Generated by Django 6.0.7 on 2026-07-29 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vaisseau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Exploration', 'Exploration'), ('Cargo', 'Cargo'), ('Transport', 'Transport'), ('Combat', 'Combat')], max_length=50)),
                ('capacite', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=100)),
                ('date_lancement', models.DateField()),
                ('statut', models.CharField(choices=[('Programmée', 'Programmée'), ('En cours', 'En cours'), ('Terminée', 'Terminée'), ('Annulée', 'Annulée')], default='Programmée', max_length=50)),
                ('vaisseau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='space_agency.vaisseau')),
            ],
        ),
    ]
