@base_url = http://127.0.0.1:8000

### 
# @name loginStaff
POST {{base_url}}/token/
Content-Type: application/json

{
    "username": "{{$dotenv username}}",
    "password": "{{$dotenv password}}"
}

### 
@token = {{loginStaff.response.body.access}}

###

GET {{base_url}}/api/missions/?statut=Programmée
Content-Type: application/json

###

GET {{base_url}}/api/lieux/
Content-Type: application/json

###

# @name createLieu
POST {{base_url}}/api/lieux/
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "nom": "Station Omega"
}


###

POST {{base_url}}/api/vaisseaux/
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "nom": "Le Bec-aux-Crocs",
    "type": "Combat",
    "capacite": 90
}

###

POST {{base_url}}/api/missions/
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "destination": 1,
    "date_lancement": "2026-08-01",
    "statut": "Programmée",
    "vaisseau": 4
}

###

PATCH {{base_url}}/api/missions/3/
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "date_lancement": "2026-10-08"
}

###

PUT {{base_url}}/api/missions/4/
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "destination": 2,
    "date_lancement": "2026-11-20",
    "statut": "Annulée",
    "vaisseau": 2
}

###

PATCH {{base_url}}/api/missions/3/changer-statut/
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "statut": "En cours"
}

###

GET {{base_url}}/api/missions/1/distance/?vers=2
Content-Type: application/json

###

# Optimise le trajet d'UN vaisseau (missions récupérées dynamiquement)
GET {{base_url}}/api/vaisseaux/1/optimiser-trajet/
Content-Type: application/json

###

# Optimise les trajets de TOUS les vaisseaux
GET {{base_url}}/api/vaisseaux/optimiser-trajets/
Content-Type: application/json

###

DELETE {{base_url}}/api/missions/4/
Authorization: Bearer {{token}}
